server:
  port: 8081

jobflow:
  storage:
    resized-image-path:  ${RESIZED_IMAGE_STORAGE_PATH:E:/cs/Jobflow/resized-images}
  retry:
    initial-backoff-seconds: 5
    multiplier: 6

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: jobflow-worker
  jackson:
    time-zone: Asia/Kolkata
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB:jobflow}?sslmode=require&options=-c%20TimeZone=UTC
    username: ${POSTGRES_USER:jobflow}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update # (worker's says 'validate' - leave that as-is, don't change it)
    show-sql: true
    properties:
      hibernate:
        type:
          "[json_format_mapper]": jackson
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: true
    listener:
      simple:
        prefetch: 5 # matches "small prefetch count" from ARCHITECTURE.md
        acknowledge-mode: manual
