server:
  port: 8080

jobflow:
  storage:
    resized-image-path:  ${RESIZED_IMAGE_STORAGE_PATH:E:/cs/Jobflow/resized-images}
  security:
    api-key: ${API_KEY}
    jwt-secret: ${JWT_SECRET}
    jwt-expiry-minutes: 120
  rate-limit:
    capacity: 20
    refill-per-second: 1
  scheduler:
    poll-interval-seconds: 10

app:
  frontend-url: http://localhost:5173

spring:
  application:
    name: jobflow-api
  jackson:
    time-zone: Asia/Kolkata
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB:jobflow}?sslmode=require&options=-c%20TimeZone=UTC
    username: ${POSTGRES_USER:jobflow}
    password: ${POSTGRES_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          "[json_format_mapper]": jackson
        format_sql: true
